namespace ZOVserver.Shared.TitanRemnants.Helper.Enumerations.Game;

public enum ShopItemHelperTable : byte
{
    FreeBox = 0,
    UpgradeMaterial = 1,
    GuaranteedBox = 2,
    GuaranteedHero = 3,
    Skin = 4,
    Item = 5,
    BrawlBox = 6,
    Ticket = 7,
    HeroPower = 8,
    CoinDoubler = 9,
    BigBox = 10,
    Keys = 11,
    WildcardPower = 12,
    EventSlot = 13,
    MediumBox = 14,
    AdBox = 15,
    Gems = 16,
    StarPoints = 17,
    QuestUnlocked = 18,
    Emote = 19,
    EmoteBundle = 20,
    RandomEmotes = 21,
    RandomEmotesForBrawler = 22,
    RandomEmoteOfRarity = 23,
    SkinAndHero = 24,
    PlayerThumbnail = 25,
    PurchaseOptionSkin = 26,
    RandomEmotesPackOfRarity = 27,
    BrawlPassTokens = 28,
    ClubFeature = 29,
    GuaranteedHeroWithLevel = 30,
    GuaranteedBoxWithLevel = 31,
    GearToken = 32,
    GearScrap = 33,
    Spray = 35,
    SprayBundle = 36,
    SpraySlot = 37,
    RecruitToken = 38,
    ChromaticToken = 39,
    PowerPointsForAnyBrawlers = 41
}