<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>ZOVserver</Authors>
        <PackageProjectUrl>https://github.com/ZOVserver</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageReference Include="ZOVserver.Shared.Contracts.Proto" Version="1.0.0"/>
    </ItemGroup>

</Project>
