# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_cp/proto/gifts_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc_cp/proto/gifts_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!grpc_cp/proto/gifts_service.proto\x12\x0cgiftsservice\"t\n\x08GiftItem\x12-\n\titem_type\x18\x01 \x01(\x0e\x32\x1a.giftsservice.GiftItemType\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x14\n\x0c\x62rawler_name\x18\x03 \x01(\t\x12\x11\n\tskin_name\x18\x04 \x01(\t\"&\n\tHighLowId\x12\x0c\n\x04high\x18\x01 \x01(\x05\x12\x0b\n\x03low\x18\x02 \x01(\x05\"t\n\x0fSendGiftRequest\x12*\n\tplayer_id\x18\x01 \x01(\x0b\x32\x17.giftsservice.HighLowId\x12%\n\x05items\x18\x02 \x03(\x0b\x32\x16.giftsservice.GiftItem\x12\x0e\n\x06reason\x18\x03 \x01(\t\"4\n\x10SendGiftResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*\xff\x01\n\x0cGiftItemType\x12\x1e\n\x1aGIFT_ITEM_TYPE_UNSPECIFIED\x10\x00\x12\x17\n\x13GIFT_ITEM_TYPE_GOLD\x10\x01\x12\x1b\n\x17GIFT_ITEM_TYPE_DIAMONDS\x10\x02\x12\x1a\n\x16GIFT_ITEM_TYPE_TICKETS\x10\x03\x12 \n\x1cGIFT_ITEM_TYPE_TOKEN_DOUBLER\x10\x04\x12\x1e\n\x1aGIFT_ITEM_TYPE_STAR_POINTS\x10\x05\x12\x1a\n\x16GIFT_ITEM_TYPE_BRAWLER\x10\x06\x12\x1f\n\x1bGIFT_ITEM_TYPE_BRAWLER_SKIN\x10\x07\x32Y\n\x0cGiftsService\x12I\n\x08SendGift\x12\x1d.giftsservice.SendGiftRequest\x1a\x1e.giftsservice.SendGiftResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_cp.proto.gifts_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GIFTITEMTYPE']._serialized_start=382
  _globals['_GIFTITEMTYPE']._serialized_end=637
  _globals['_GIFTITEM']._serialized_start=51
  _globals['_GIFTITEM']._serialized_end=167
  _globals['_HIGHLOWID']._serialized_start=169
  _globals['_HIGHLOWID']._serialized_end=207
  _globals['_SENDGIFTREQUEST']._serialized_start=209
  _globals['_SENDGIFTREQUEST']._serialized_end=325
  _globals['_SENDGIFTRESPONSE']._serialized_start=327
  _globals['_SENDGIFTRESPONSE']._serialized_end=379
  _globals['_GIFTSSERVICE']._serialized_start=639
  _globals['_GIFTSSERVICE']._serialized_end=728
# @@protoc_insertion_point(module_scope)
