# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_cp/proto/messages_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc_cp/proto/messages_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$grpc_cp/proto/messages_service.proto\x12\x0fmessagesservice\"&\n\tHighLowId\x12\x0c\n\x04high\x18\x01 \x01(\x05\x12\x0b\n\x03low\x18\x02 \x01(\x05\"1\n\x0bMessageItem\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x14\n\x0c\x66rom_support\x18\x02 \x01(\x08\"t\n\x13SendMessagesRequest\x12-\n\tplayer_id\x18\x01 \x01(\x0b\x32\x1a.messagesservice.HighLowId\x12.\n\x08messages\x18\x02 \x03(\x0b\x32\x1c.messagesservice.MessageItem\"8\n\x14SendMessagesResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2n\n\x0fMessagesService\x12[\n\x0cSendMessages\x12$.messagesservice.SendMessagesRequest\x1a%.messagesservice.SendMessagesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_cp.proto.messages_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HIGHLOWID']._serialized_start=57
  _globals['_HIGHLOWID']._serialized_end=95
  _globals['_MESSAGEITEM']._serialized_start=97
  _globals['_MESSAGEITEM']._serialized_end=146
  _globals['_SENDMESSAGESREQUEST']._serialized_start=148
  _globals['_SENDMESSAGESREQUEST']._serialized_end=264
  _globals['_SENDMESSAGESRESPONSE']._serialized_start=266
  _globals['_SENDMESSAGESRESPONSE']._serialized_end=322
  _globals['_MESSAGESSERVICE']._serialized_start=324
  _globals['_MESSAGESSERVICE']._serialized_end=434
# @@protoc_insertion_point(module_scope)
