# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_cp.proto import shop_service_pb2 as grpc__cp_dot_proto_dot_shop__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc_cp/proto/shop_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShopServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePromotion = channel.unary_unary(
                '/shopservice.ShopService/CreatePromotion',
                request_serializer=grpc__cp_dot_proto_dot_shop__service__pb2.CreatePromotionRequest.SerializeToString,
                response_deserializer=grpc__cp_dot_proto_dot_shop__service__pb2.CreatePromotionResponse.FromString,
                _registered_method=True)
        self.DeletePromotion = channel.unary_unary(
                '/shopservice.ShopService/DeletePromotion',
                request_serializer=grpc__cp_dot_proto_dot_shop__service__pb2.DeletePromotionRequest.SerializeToString,
                response_deserializer=grpc__cp_dot_proto_dot_shop__service__pb2.DeletePromotionResponse.FromString,
                _registered_method=True)
        self.GetPromotionHistory = channel.unary_unary(
                '/shopservice.ShopService/GetPromotionHistory',
                request_serializer=grpc__cp_dot_proto_dot_shop__service__pb2.GetPromotionHistoryRequest.SerializeToString,
                response_deserializer=grpc__cp_dot_proto_dot_shop__service__pb2.GetPromotionHistoryResponse.FromString,
                _registered_method=True)


class ShopServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePromotion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePromotion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPromotionHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShopServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePromotion': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePromotion,
                    request_deserializer=grpc__cp_dot_proto_dot_shop__service__pb2.CreatePromotionRequest.FromString,
                    response_serializer=grpc__cp_dot_proto_dot_shop__service__pb2.CreatePromotionResponse.SerializeToString,
            ),
            'DeletePromotion': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePromotion,
                    request_deserializer=grpc__cp_dot_proto_dot_shop__service__pb2.DeletePromotionRequest.FromString,
                    response_serializer=grpc__cp_dot_proto_dot_shop__service__pb2.DeletePromotionResponse.SerializeToString,
            ),
            'GetPromotionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPromotionHistory,
                    request_deserializer=grpc__cp_dot_proto_dot_shop__service__pb2.GetPromotionHistoryRequest.FromString,
                    response_serializer=grpc__cp_dot_proto_dot_shop__service__pb2.GetPromotionHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shopservice.ShopService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shopservice.ShopService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShopService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePromotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shopservice.ShopService/CreatePromotion',
            grpc__cp_dot_proto_dot_shop__service__pb2.CreatePromotionRequest.SerializeToString,
            grpc__cp_dot_proto_dot_shop__service__pb2.CreatePromotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePromotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shopservice.ShopService/DeletePromotion',
            grpc__cp_dot_proto_dot_shop__service__pb2.DeletePromotionRequest.SerializeToString,
            grpc__cp_dot_proto_dot_shop__service__pb2.DeletePromotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPromotionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shopservice.ShopService/GetPromotionHistory',
            grpc__cp_dot_proto_dot_shop__service__pb2.GetPromotionHistoryRequest.SerializeToString,
            grpc__cp_dot_proto_dot_shop__service__pb2.GetPromotionHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
