# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_cp/proto/shop_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc_cp/proto/shop_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n grpc_cp/proto/shop_service.proto\x12\x0bshopservice\"]\n\rPromotionItem\x12\x11\n\titem_type\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x14\n\x0c\x62rawler_name\x18\x03 \x01(\t\x12\x11\n\tskin_name\x18\x04 \x01(\t\"\xee\x01\n\x16\x43reatePromotionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08is_daily\x18\x02 \x01(\x08\x12\x12\n\nstart_time\x18\x03 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x04 \x01(\x03\x12\r\n\x05price\x18\x05 \x01(\x01\x12\x11\n\told_price\x18\x06 \x01(\x01\x12\x12\n\nprice_type\x18\x07 \x01(\x05\x12\x12\n\nbackground\x18\x08 \x01(\t\x12\x19\n\x11show_to_new_users\x18\t \x01(\x08\x12)\n\x05items\x18\n \x03(\x0b\x32\x1a.shopservice.PromotionItem\"Q\n\x17\x43reatePromotionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0cpromotion_id\x18\x03 \x01(\t\".\n\x16\x44\x65letePromotionRequest\x12\x14\n\x0cpromotion_id\x18\x01 \x01(\t\";\n\x17\x44\x65letePromotionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1c\n\x1aGetPromotionHistoryRequest\"u\n\x15PromotionHistoryEntry\x12\x14\n\x0cpromotion_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\x03\x12\x12\n\nstart_time\x18\x04 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\x03\"w\n\x1bGetPromotionHistoryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x36\n\npromotions\x18\x03 \x03(\x0b\x32\".shopservice.PromotionHistoryEntry2\xb3\x02\n\x0bShopService\x12\\\n\x0f\x43reatePromotion\x12#.shopservice.CreatePromotionRequest\x1a$.shopservice.CreatePromotionResponse\x12\\\n\x0f\x44\x65letePromotion\x12#.shopservice.DeletePromotionRequest\x1a$.shopservice.DeletePromotionResponse\x12h\n\x13GetPromotionHistory\x12\'.shopservice.GetPromotionHistoryRequest\x1a(.shopservice.GetPromotionHistoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_cp.proto.shop_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROMOTIONITEM']._serialized_start=49
  _globals['_PROMOTIONITEM']._serialized_end=142
  _globals['_CREATEPROMOTIONREQUEST']._serialized_start=145
  _globals['_CREATEPROMOTIONREQUEST']._serialized_end=383
  _globals['_CREATEPROMOTIONRESPONSE']._serialized_start=385
  _globals['_CREATEPROMOTIONRESPONSE']._serialized_end=466
  _globals['_DELETEPROMOTIONREQUEST']._serialized_start=468
  _globals['_DELETEPROMOTIONREQUEST']._serialized_end=514
  _globals['_DELETEPROMOTIONRESPONSE']._serialized_start=516
  _globals['_DELETEPROMOTIONRESPONSE']._serialized_end=575
  _globals['_GETPROMOTIONHISTORYREQUEST']._serialized_start=577
  _globals['_GETPROMOTIONHISTORYREQUEST']._serialized_end=605
  _globals['_PROMOTIONHISTORYENTRY']._serialized_start=607
  _globals['_PROMOTIONHISTORYENTRY']._serialized_end=724
  _globals['_GETPROMOTIONHISTORYRESPONSE']._serialized_start=726
  _globals['_GETPROMOTIONHISTORYRESPONSE']._serialized_end=845
  _globals['_SHOPSERVICE']._serialized_start=848
  _globals['_SHOPSERVICE']._serialized_end=1155
# @@protoc_insertion_point(module_scope)
