# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_cp.proto import statistics_service_pb2 as grpc__cp_dot_proto_dot_statistics__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc_cp/proto/statistics_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StatisticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGlobalStats = channel.unary_unary(
                '/statisticsservice.StatisticsService/GetGlobalStats',
                request_serializer=grpc__cp_dot_proto_dot_statistics__service__pb2.Empty.SerializeToString,
                response_deserializer=grpc__cp_dot_proto_dot_statistics__service__pb2.GlobalStatsResponse.FromString,
                _registered_method=True)
        self.GetPlayerStats = channel.unary_unary(
                '/statisticsservice.StatisticsService/GetPlayerStats',
                request_serializer=grpc__cp_dot_proto_dot_statistics__service__pb2.PlayerStatsRequest.SerializeToString,
                response_deserializer=grpc__cp_dot_proto_dot_statistics__service__pb2.PlayerStatsResponse.FromString,
                _registered_method=True)


class StatisticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGlobalStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlayerStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatisticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGlobalStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalStats,
                    request_deserializer=grpc__cp_dot_proto_dot_statistics__service__pb2.Empty.FromString,
                    response_serializer=grpc__cp_dot_proto_dot_statistics__service__pb2.GlobalStatsResponse.SerializeToString,
            ),
            'GetPlayerStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayerStats,
                    request_deserializer=grpc__cp_dot_proto_dot_statistics__service__pb2.PlayerStatsRequest.FromString,
                    response_serializer=grpc__cp_dot_proto_dot_statistics__service__pb2.PlayerStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'statisticsservice.StatisticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('statisticsservice.StatisticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatisticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGlobalStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statisticsservice.StatisticsService/GetGlobalStats',
            grpc__cp_dot_proto_dot_statistics__service__pb2.Empty.SerializeToString,
            grpc__cp_dot_proto_dot_statistics__service__pb2.GlobalStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlayerStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statisticsservice.StatisticsService/GetPlayerStats',
            grpc__cp_dot_proto_dot_statistics__service__pb2.PlayerStatsRequest.SerializeToString,
            grpc__cp_dot_proto_dot_statistics__service__pb2.PlayerStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
