# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_cp.proto import user_service_pb2 as grpc__cp_dot_proto_dot_user__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc_cp/proto/user_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BanUser = channel.unary_unary(
                '/userservice.UserManagement/BanUser',
                request_serializer=grpc__cp_dot_proto_dot_user__service__pb2.BanUserRequest.SerializeToString,
                response_deserializer=grpc__cp_dot_proto_dot_user__service__pb2.UserResponse.FromString,
                _registered_method=True)
        self.LockUserAccount = channel.unary_unary(
                '/userservice.UserManagement/LockUserAccount',
                request_serializer=grpc__cp_dot_proto_dot_user__service__pb2.LockUserRequest.SerializeToString,
                response_deserializer=grpc__cp_dot_proto_dot_user__service__pb2.LockUserResponse.FromString,
                _registered_method=True)
        self.UnlockUserAccount = channel.unary_unary(
                '/userservice.UserManagement/UnlockUserAccount',
                request_serializer=grpc__cp_dot_proto_dot_user__service__pb2.UserIdRequest.SerializeToString,
                response_deserializer=grpc__cp_dot_proto_dot_user__service__pb2.UserResponse.FromString,
                _registered_method=True)


class UserManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BanUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LockUserAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockUserAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BanUser': grpc.unary_unary_rpc_method_handler(
                    servicer.BanUser,
                    request_deserializer=grpc__cp_dot_proto_dot_user__service__pb2.BanUserRequest.FromString,
                    response_serializer=grpc__cp_dot_proto_dot_user__service__pb2.UserResponse.SerializeToString,
            ),
            'LockUserAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.LockUserAccount,
                    request_deserializer=grpc__cp_dot_proto_dot_user__service__pb2.LockUserRequest.FromString,
                    response_serializer=grpc__cp_dot_proto_dot_user__service__pb2.LockUserResponse.SerializeToString,
            ),
            'UnlockUserAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockUserAccount,
                    request_deserializer=grpc__cp_dot_proto_dot_user__service__pb2.UserIdRequest.FromString,
                    response_serializer=grpc__cp_dot_proto_dot_user__service__pb2.UserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'userservice.UserManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('userservice.UserManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BanUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserManagement/BanUser',
            grpc__cp_dot_proto_dot_user__service__pb2.BanUserRequest.SerializeToString,
            grpc__cp_dot_proto_dot_user__service__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LockUserAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserManagement/LockUserAccount',
            grpc__cp_dot_proto_dot_user__service__pb2.LockUserRequest.SerializeToString,
            grpc__cp_dot_proto_dot_user__service__pb2.LockUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlockUserAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userservice.UserManagement/UnlockUserAccount',
            grpc__cp_dot_proto_dot_user__service__pb2.UserIdRequest.SerializeToString,
            grpc__cp_dot_proto_dot_user__service__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
