# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_cp/proto/user_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc_cp/proto/user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n grpc_cp/proto/user_service.proto\x12\x0buserservice\"M\n\rUserIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12+\n\x0bhigh_low_id\x18\x02 \x01(\x0b\x32\x16.userservice.HighLowId\"w\n\x0e\x42\x61nUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12+\n\x0bhigh_low_id\x18\x02 \x01(\x0b\x32\x16.userservice.HighLowId\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x17\n\x0funban_timestamp\x18\x04 \x01(\x03\"f\n\x0fLockUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12+\n\x0bhigh_low_id\x18\x02 \x01(\x0b\x32\x16.userservice.HighLowId\x12\x15\n\rrecovery_code\x18\x03 \x01(\t\"0\n\x0cUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"K\n\x10LockUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rrecovery_code\x18\x03 \x01(\t\"&\n\tHighLowId\x12\x0c\n\x04high\x18\x01 \x01(\x05\x12\x0b\n\x03low\x18\x02 \x01(\x05\x32\xef\x01\n\x0eUserManagement\x12\x41\n\x07\x42\x61nUser\x12\x1b.userservice.BanUserRequest\x1a\x19.userservice.UserResponse\x12N\n\x0fLockUserAccount\x12\x1c.userservice.LockUserRequest\x1a\x1d.userservice.LockUserResponse\x12J\n\x11UnlockUserAccount\x12\x1a.userservice.UserIdRequest\x1a\x19.userservice.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_cp.proto.user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERIDREQUEST']._serialized_start=49
  _globals['_USERIDREQUEST']._serialized_end=126
  _globals['_BANUSERREQUEST']._serialized_start=128
  _globals['_BANUSERREQUEST']._serialized_end=247
  _globals['_LOCKUSERREQUEST']._serialized_start=249
  _globals['_LOCKUSERREQUEST']._serialized_end=351
  _globals['_USERRESPONSE']._serialized_start=353
  _globals['_USERRESPONSE']._serialized_end=401
  _globals['_LOCKUSERRESPONSE']._serialized_start=403
  _globals['_LOCKUSERRESPONSE']._serialized_end=478
  _globals['_HIGHLOWID']._serialized_start=480
  _globals['_HIGHLOWID']._serialized_end=518
  _globals['_USERMANAGEMENT']._serialized_start=521
  _globals['_USERMANAGEMENT']._serialized_end=760
# @@protoc_insertion_point(module_scope)
