<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>ZOVserver</Authors>
        <PackageProjectUrl>https://github.com/ZOVserver</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="StackExchange.Redis" Version="2.11.3"/>
        <PackageReference Include="ZOVserver.Shared.Abstractions" Version="1.0.0" />
    </ItemGroup>

</Project>
